---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: nodes
  require_chef_for_busser: false
  require_ruby_for_busser: false
  # ansible_verbose: true
  ansible_diff: true
  
platforms:
  - name: centos-6.7

verifier:
  name: inspec

suites:
  - name: default
    verifier:
    inspec_tests:
      - test/integration/default
    provisioner:
      playbook: test/integration/default/test.yml

